#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Ejecutando Linter y TypeScript antes de hacer commit..."

npm run lint

npx tsc --noEmit

echo "✅ Código limpio. Procediendo con el commit..."